"""initial

Revision ID: 63fd9802c4d3
Revises:
Create Date: 2024-05-07 09:25:31.731952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fd9802c4d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('precipitation', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('sea_level_pressure', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('surface_pressure', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('wind_speed', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('wind_direction', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
